cleanWorkspace:
	rm __* -rf

logClean:
	rm -f logs/*.csv logs/*.txt

driversClean:
	rm -rf spFunDrivers/*.c spFunDrivers/*.so spFunDrivers/*.py spFunDrivers/__* spFunDrivers/*_discrepancy

reset: cleanWorkspace logClean driversClean
